CREATE DATABASE INFO;

USE INFO;

CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL 
);

INSERT INTO STUDENT VALUES(1,  "ABDUL KABEER", 24);
INSERT INTO STUDENT VALUES(2,  "ARHAM", 18);
INSERT INTO STUDENT VALUES(3,  "MUHAMMAD ARSALAN", 20);
INSERT INTO STUDENT VALUES(4,  "ALI", 21);
INSERT INTO STUDENT VALUES(5,  "MUZAMMIL", 19);
INSERT INTO STUDENT VALUES(6,  "MURTUZA HUSSAIN", 23);


SELECT * FROM STUDENT;


